[project]
name = "gen"
version = "0.1.0"
description = "GeneraciÃ³n de sitio de Sin Dioses"
requires-python = ">=3.13,<3.14"
dependencies = [
    "nikola[extras]>=8.3.3",
    "ghp-import>=2.1.0",
]

[tool.ruff]
line-length = 160

[tool.ruff.lint]
extend-select = [
    "I",
]
